# Site settings
title: "Universitetsparken"
description: "Grundejerforeningen for omr√•det ved Tinbergens Alle"
baseurl: ""
url: ""

# Paginate
paginate: 5
paginate_path: "/page/:num"

# Build settings
markdown: kramdown
sass:
  style: compressed
gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, README.md]
